# Generated by Django 2.2.2 on 2019-06-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_created']},
        ),
    ]
